name: Bitcoin
description: Adapter that connects Chainlink oracle nodes to the bitcoin network faciliating BTC JSON-RPC calls
node_identifier: bitcoin
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Bitcoin
    url: https://bitcoin.org/en/
parameters:
  - rpc_command
  - tx_id
  - verbose
